set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab smartindent
set nocompatible ruler laststatus=2 showcmd showmode number
set incsearch ignorecase smartcase hlsearch
set nowrap
colorscheme molokai
syntax on
highlight Comment cterm=bold
highlight Normal ctermbg=none
highlight NonText ctermbg=none
